### ISSUE TITLE
Is there any way to convert a PEM format cert to p7b format?

### ISSUE THREAD

**Issue by pkking** [RustCrypto/formats#1030] opened 2023-04-28 03:01 UTC
Some backgrouds:
Im try to sign a PKCS#7 signed data, but i can just using [openssl-rs](https://crates.io/crates/openssl) to generate a x509 certificate in PEM/DER format.
So im curious if there's any way to convert the x509 cert into p7b format.
Any suggestion appreciated!

**Comment by tarcieri** [comment] 2023-04-28 16:11
Probably a question for @carl-wallace.

I believe the bulk of this functionality can be found in [`SignedDataContent`](https://docs.rs/pkcs7/latest/pkcs7/signed_data_content/struct.SignedDataContent.html), though there is no code to actually build the data structure from a certificate+chain, nor is there handling for PEM encoding.

**Comment by carl-wallace** [comment] 2023-04-28 16:20
There's no convenience method to convert a PEM-encoded certificate to a certs-only SignedData (assuming this is what is desired) but the parts to make one ought be there. I could prepare one next week if you like.

**Comment by pkking** [comment] 2023-04-28 16:30
That would be great😀

**Comment by carl-wallace** [comment] 2023-04-30 19:42
See #1032

**Comment by tarcieri** [comment] 2023-04-30 21:27
#1032 is merged.

@pkking can you try it out and if it looks good, I can cut a release?

**Comment by pkking** [comment] 2023-05-01 05:59
On my vocation, will try it later😀

**Comment by pkking** [comment] 2023-05-03 01:22
Hi @carl-wallace , im trying to use the new try_from traits, but i got some error:
```
    // $ openssl genrsa  -out domain.key 2048
    // $ openssl req -key domain.key -new -out domain.csr
    // $ openssl x509 -signkey domain.key -in domain.csr -req -days 365 -out certificate.pem
    let ee_cert_buf = include_bytes!("certificate.pem");
    // $ openssl crl2pkcs7 -nocrl -certfile certificate.pem -out certificate.p7b -outform PEM
    let p7b_ee_buf = include_bytes!("certificate.p7b");
    let ee_cert: x509_cert::Certificate = x509_cert::Certificate::from_pem(ee_cert_buf).unwrap();
    let p7b_ee = ContentInfo::try_from(ee_cert).unwrap();
    let p7b_ee_buf2 = p7b_ee.to_der().unwrap();
    assert_eq!(p7b_ee_buf, p7b_ee_buf2.as_slice());
```
the compile error:
```
error[E0277]: the trait bound `ContentInfo: From<CertificateInner>` is not satisfied
  --> src\main.rs:26:18
   |
26 |     let p7b_ee = ContentInfo::try_from(ee_cert).unwrap();
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<CertificateInner>` is not implemented for `ContentInfo`
   |
   = help: the following other types implement trait `TryFrom<T>`:
             <ContentInfo as TryFrom<Vec<x509_cert::certificate::Certificate>>>
             <ContentInfo as TryFrom<x509_cert::certificate::Certificate>>
   = note: required for `CertificateInner` to implement `Into<ContentInfo>`
   = note: required for `ContentInfo` to implement `TryFrom<CertificateInner>`
```

**Comment by carl-wallace** [comment] 2023-05-03 03:00
Your code works (with a mod) as a test in the cms crate but I see the same error in a standalone binary. Will give a look but it will be a few days. I've not caught up on the changes to add profiles yet so not sure offhand what the issue is. Changing to TryFrom<CertificateInner> in the library results in the error "no `CertificateInner` in `certificate`" when building the binary.

The mod to your test code is to generate the p7b in DER format. As written your assert is comparing PEM to DER.

**Comment by carl-wallace** [comment] 2023-05-03 18:03
@baloo @tarcieri does the error above ring any bells?

**Comment by baloo** [comment] 2023-05-03 18:52
yeah, I'd say you have two versions of x509-cert.

**Comment by tarcieri** [comment] 2023-05-03 18:54
You can try importing it with a `patch.crates-io` directive in Cargo.toml:

```toml
[patch.crates-io.cms]
path = "/path/to/formats/cms"
```

**Comment by tarcieri** [comment] 2023-05-03 18:54
Or I can just cut a prerelease/release and hope for the best

**Comment by carl-wallace** [comment] 2023-05-03 19:40
@pkking try the following (provided by @tarcieri) in your cargo.toml. this did the trick for me. without this there were two versions of x509-cert in play that had different certificate structures (as described by @baloo).

```
[dependencies]
x509-cert = { version = "*", features = ["pem"] }
cms = "*"

[patch.crates-io]
x509-cert = { git = "https://github.com/RustCrypto/formats" }
cms = { git = "https://github.com/RustCrypto/formats" }
```

**Comment by pkking** [comment] 2023-05-04 11:57
@carl-wallace @tarcieri Thanks, it works for me, then i tested and the generate the cert generated by openssl and cms was slightly different, but i think it does not matter.
```
# openssl pkcs7 -print -in certificate.p7b  -inform DER > p7b.txt
# openssl pkcs7 -print -in ../certificate1.p7b  -inform DER > p7b1.txt
# diff -u p7b.txt p7b1.txt
--- p7b.txt     2023-05-04 19:55:18.725544700 +0800
+++ p7b1.txt    2023-05-04 19:55:30.459161100 +0800
@@ -71,11 +71,11 @@
           00f0 - 29 a4 47 63 90 14 a2 ca-ea e3 cd 8d 81 16 42   ).Gc..........B
           00ff - b5                                             .
     crl:
-      <ABSENT>
+      <EMPTY>
     signer_info:
       <EMPTY>
 -----BEGIN PKCS7-----
-MIIDQAYJKoZIhvcNAQcCoIIDMTCCAy0CAQExADALBgkqhkiG9w0BBwGgggMVMIID
+MIIDQgYJKoZIhvcNAQcCoIIDMzCCAy8CAQExADALBgkqhkiG9w0BBwGgggMVMIID
 ETCCAfkCFBJvhBEWu3F0tQmpJi6qdxwSMjqeMA0GCSqGSIb3DQEBCwUAMEUxCzAJ
 BgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5l
 dCBXaWRnaXRzIFB0eSBMdGQwHhcNMjMwNTA0MTEzMTUyWhcNMjQwNTAzMTEzMTUy
@@ -92,5 +92,5 @@
 GqaIUZdry/BJcHov0y6qXjdStgkObVOKowJZEAmXsRtKvD0M1Z3NZ74ezVeT0Y4q
 LbGg4DW28c5MGa9WrPLETIUjx3ltAEUwbnOeb4oIkw3z41iQre4wl4/rR6qjGSMk
 gStvMFUcSY2O1rmpXQUBix/3+hjzOSGikqlvY2OP+DhM4t8LEAvOtT709nIP7jse
-iLEppEdjkBSiyurjzY2BFkK1MQA=
+iLEppEdjkBSiyurjzY2BFkK1oQAxAA==
 -----END PKCS7-----
```

**Comment by pkking** [comment] 2023-05-04 13:03
Feel free to close this ticket if a new release avaiable :)

**Closed** 2023-05-04 15:23 UTC
