### ISSUE TITLE
der: Support custom error types.

### ISSUE THREAD

**Issue by turbocool3r** [RustCrypto/formats#1053] opened 2023-05-06 19:52 UTC
I'm currently developing a library for parsing the [Image4](https://www.theiphonewiki.com/wiki/IMG4_File_Format) format found in boot images on Apple devices which is based on DER. This format has some constraints not related to the DER and I'd like to provide a custom error type that implements `From<der::Error>` and has some additional variants I need. Is this something that would be possible to add?

I think the best way to do it is to add associated `Error` types in the `Decode` and `Encode` traits and wherever needed. I'll be happy to provide a PR.

Here is an [example](https://lapo.it/asn1js/#MIIJ0BYESU00TQIBADGCAg3_hOqFnEKCAgQwggIAFgRNQU5CMYIB9v-E6oWcUIIBiTCCAYUWBE1BTlAxggF7_4bjwdxoOjA4FgRscG5oBDDDBlteT6LShlivrY4dzaW3xP3d7bc1D9kKvCBCZr_hYi12L_Bzay7J2b5xeRmQ5ab_h5PB3Gg6MDgWBHJwbmgEMMMGW15PotKGWK-tjh3NpbfE_d3ttzUP2Qq8IEJmv-FiLXYv8HNrLsnZvnF5GZDlpv-Eqo2SRBEwDxYERUNJRAIHEkAiPmtAHv-EmqGSUAwwChYEQ0hJUAICYCD_hJK9pEQLMAkWBEJPUkQCAQb_hJrBpE8LMAkWBENQUk8BAf__hJrNikMLMAkWBENTRUMBAf__hZqRnk0LMAkWBFNET00CAQH_hJqVoE8LMAkWBENFUE8CAQH_huO9xG8LMAkWBGxvYm8BAf__h7PV0mQaMBgWBHZ1aWQEEN31xifRUkBwpxhzGz9lv6r_hvPN0mg6MDgWBG5zaWgEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP-Gi9Xwa10wWxYEYXV4azFT_4SqrYpZCzAJFgRFS0VZAQH__4SinaZUOjA4FgRER1NUBDARajTIzvXgOyvoUAwDDCSA4G_bxHtfY8zMu_XIRdsKieuOBS0ATI5apyN_SUlJLYQEaDBmAjEA-S2ynDnz7slo6nXpkDhCNRKbe7s3eN6wsKa0XS0Ja_AjG1Jq5jV233qwb49Ckpe6AjEAnxwY17c-swX0J1T9WyM6zOMSFURBGE1PsDXqXznrGbqkAwhwCsyCVdmuSfCsheE-MIIHSDCCAkcwggHNoAMCAQICEAhI0iDrKk9NJFKVvfYZJ18wCgYIKoZIzj0EAwMwUzEnMCUGA1UEAwweQmFzaWMgQXR0ZXN0YXRpb24gVXNlciBSb290IENBMRMwEQYDVQQKDApBcHBsZSBJbmMuMRMwEQYDVQQIDApDYWxpZm9ybmlhMB4XDTE5MDgyMTE5MDEyOFoXDTMyMDMyMjAwMDAwMFowUzEnMCUGA1UEAwweQmFzaWMgQXR0ZXN0YXRpb24gVXNlciBTdWIgQ0EyMRMwEQYDVQQKDApBcHBsZSBJbmMuMRMwEQYDVQQIDApDYWxpZm9ybmlhMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE279T5TkssXWjE2Lr4XjnHAaSd4orF_fThaMjX1KIRw-4M1s8I6uPqTmn7Ye4LJLgJ4NMC1uJmAtHl4NeKD_Vx0UJ9tbMObJP-RB8D4_f0X7Pz2pfbiBnHgtn89wZTqTco2YwZDASBgNVHRMBAf8ECDAGAQH_AgEAMB8GA1UdIwQYMBaAFIPloyGesHTD-WGQ_ZdOIxB2pKPyMB0GA1UdDgQWBBSIAUvviAJ3SqrNcA6snIZbp_-HcTAOBgNVHQ8BAf8EBAMCAQYwCgYIKoZIzj0EAwMDaAAwZQIxAJFgWPHw7oBQr0-eBBg8e_E6-mOiOrJ_PlKorwK0lhZPmNLs76Jd4raGsy3XSBHADwIwb13oAwg7Bub0MUqOMJiQyupt7qnOtFszLGeCC_7W8adwsq-AosbADZ8B4f-WSF4WMIIE-TCCBH6gAwIBAgIGAYadEe8nMAoGCCqGSM49BAMDMFMxJzAlBgNVBAMMHkJhc2ljIEF0dGVzdGF0aW9uIFVzZXIgU3ViIENBMjETMBEGA1UECgwKQXBwbGUgSW5jLjETMBEGA1UECAwKQ2FsaWZvcm5pYTAeFw0yMzAyMjgxMjA3MjNaFw0yMzAzMDMxMjA3MjNaMIGRMUkwRwYDVQQDDEAzMWJjOWE3ZTRjOWYyNzZkMTI2MTEzMDdjNTczYTY5MWE3MDdjNDhhNDFjNTg4YTViMmI3YmEyOTgwOTM5NTBjMRowGAYDVQQLDBFCQUEgQ2VydGlmaWNhdGlvbjETMBEGA1UECgwKQXBwbGUgSW5jLjETMBEGA1UECAwKQ2FsaWZvcm5pYTB2MBAGByqGSM49AgEGBSuBBAAiA2IABDiY3FMXu1cS88cuBrQBzYE6eHB2LsNpPV15uRcc5YOZTfRGmULP2tUTfSwYYKkyR3VwGBD3edLDjFoul0oiB_iYG3yFfzRgPLFcrLUWbG-FScbxy55Fvv_GXVUYlnag3aOCAuAwggLcMAwGA1UdEwEB_wQCMAAwDgYDVR0PAQH_BAQDAgTwMC8GCSqGSIb3Y2QIBAQiMCC_iEwDAgEBv4hNBwIFAP4AAAC_iE4DAgEBv4hTAwIBADCCAeUGCiqGSIb3Y2QGAQ8EggHVMYIB0f-E6oWcUIIBWDCCAVQWBE1BTlAxggFK_4SSvaRECzAJFgRCT1JEAgEG_4eTvdxoDDAKFgRyb25ooQIFAP-G473EbwswCRYEbG9ibwEB__-FmpGeTQswCRYEU0RPTQIBAf-G48HcaAwwChYEbHBuaKACBQD_h5PB3Gg6MDgWBHJwbmgEMMMGW15PotKGWK-tjh3NpbfE_d3ttzUP2Qq8IEJmv-FiLXYv8HNrLsnZvnF5GZDlpv-EkrmGSAwwChYEQk5DSKECBQD_hJrNikMLMAkWBENTRUMBAf__hJqhklAMMAoWBENISVACAmAg_4SKtZxNDDAKFgRBTU5NoQIFAP-EmsGkTwswCRYEQ1BSTwEB__-G883SaAwwChYEbnNpaKACBQD_h5u1xDUMMAoWBHNtYjWhAgUA_4SqjZJEETAPFgRFQ0lEAgcSQCI-a0Ae_4SalaBPCzAJFgRDRVBPAgEB_4T6iZRQaTBnFgRPQkpQMV__hKrBpE8MMAoWBEVQUk-hAgUA_4SiwaRPDDAKFgREUFJPoQIFAP-Eqs2KQwwwChYERVNFQ6ECBQD_hKLNikMMMAoWBERTRUOhAgUA_4SinaZUDDAKFgRER1NUoAIFADBUBgkqhkiG92NkCAUERzBFpAMCAQ2_iTADAgEBv4kxAwIBAL-JMgMCAQG_iTMDAgEBpQYEBHNzY2G_iTYDAgEIv4k3AwIBAL-JOQMCAQC_iToDAgEAMEwGCSqGSIb3Y2QIBwQ_MD2_ingIBAYxMy4yLjG_in8DAgEAv4sAAwIBAL-LAQMCAQC_iwIDAgEAv4sDAwIBAL-LBAMCAQC_iwUDAgEAMAoGCCqGSM49BAMDA2kAMGYCMQDchz1p19_OLTsLRnbY94Bw-4emKBUu2N1cV-LHGBRQHFQiCWQqbiBf8MkRAt9NaaoCMQCXNaGwrwIcmsJWcG1C1LnTpz_8AEigPEvQc35TsE9ZMuWGgS8DrmDh0zdpVq0KK48) of a file I want to parse if you'd like to understand my case better. This recursive structure also creates compile-time recursion when used with the `read_nested` method btw. Should I file an issue?

**Comment by tarcieri** [comment] 2023-05-06 20:05
Seems like you already filed an issue :wink:

Yeah, we do something like this in the `ssh-encoding` crate: https://docs.rs/ssh-encoding/latest/ssh_encoding/trait.Decode.html

I'm generally supportive of it, although it'd be a pretty big change in terms of overall code churn. Probably worth it, though.

**Comment by turbocool3r** [comment] 2023-05-07 00:42
Nice! I'll try to make a PR when I'll have some time.

**Comment by tarcieri** [comment] 2023-05-08 16:36
I don't understand what the problem is. Can you explain which error types are incompatible in this case?

Did you use the same approach as `ssh-encoding` where the associated error type is bounded on `From<der::Error>`?

**Comment by turbocool3r** [comment] 2023-05-08 17:34
Yes, the approach is the same. The problem is when you set a trait bound like `DerOrd + Decode<'a>` there are two `Error` types that are not necessarily compatible. If you write something like:
```rust
fn foo<'a, T: DerOrd + Decode<'a>>(bytes: &'a [u8], bar: &T) -> Result<T, <T as Decode>::Error> {
    let baz = T::from_der(bytes)?;
    let a = baz.der_cmp(bar)?;
    ...
    Ok(baz)
}
```

there will be a compiler error because `<T as Decode>::Error` might not be constructible from `<T as DerOrd>::Error`.

**Comment by tarcieri** [comment] 2023-05-08 17:36
So, this line?

```rust
 let a = baz.der_cmp(bar)?;
```

But if there's a `From<der::Error>` bound on `<T as Decode>::Error`, that should take care of it.

**Comment by turbocool3r** [comment] 2023-05-08 17:57
It isn't really possible to not add an associated `Error` type to `DerOrd` as well as the `Encode`/`Decode` traits if we want to use the latter traits while implementing `DerOrd`. [Here](https://github.com/RustCrypto/formats/blob/bee8a6ea34f978ca474e4e42fceb158f9a39d6dd/der/src/ord.rs#L28) is a good example of why `der_cmp` can't return `der::Error` in that case.

**Comment by tarcieri** [comment] 2023-05-08 17:59
How about only parameterizing the type for `Decode`/`DecodeValue`?

**Comment by dishmaker** [comment] 2023-09-25 11:09
I've done custom error handling for `Decode` / `DecodeValue`.
It works perfectly but I had to use `std::result::Result` everywhere.

Also renamed `Error` to `DerError`.

```rust

/// Reader trait which reads DER-encoded input.
pub trait Reader<'r>: Sized {
    /// Error returned by the reader
    type ERR: From<DerError> + From<ErrorKind> + DerDebugErr;

    fn read_nested<'n, T, F>(&'n mut self, len: Length, f: F) -> std::result::Result<T, Self::ERR>
    where
        F: FnOnce(&mut NestedReader<'n, Self>) -> std::result::Result<T, Self::ERR>,
    {
        let mut reader = NestedReader::new(self, len)?;
        let ret = f(&mut reader).wrap_err_nested::<T>()?;
        reader
            .finish(ret)
            .wrap_err_field("finish()")
            .wrap_err_nested::<T>()
    }
```

Note: `wrap_err_nested` and `wrap_err_field` are custom generic `fn`s that do nothing till overriden for ERR type.
So these functions are zero-cost (they optimize out at compile-time).

```rust
/// Used to pretty-print errors
pub trait DerDebugErr {
    /// Called when reading a nested sequence
    fn wrap_err_nested<X>(self) -> Self;

    /// Called when reading a field
    /// 
    /// auto-generated calls in `#[derive(Sequence)]`
    fn wrap_err_field(self, field_name: &str) -> Self;

    /// Called when reading an entry in Vec sequence/set
    fn wrap_err_index(self, index: usize) -> Self;
```

**Comment by tarcieri** [comment] 2024-08-18 14:37
Fixed in #1055

**Closed by tarcieri** 2024-08-18 14:37 UTC

**Comment by dishmaker** [comment] 2024-10-04 12:46
Omg why are these generic Errors on a `Decode` trait :( 😢 😭 

It would be a lot better on `Reader` trait.
```rust
/// Reader trait which reads DER-encoded input.
pub trait Reader<'r>: Sized {
    /// Error returned by the reader
    type ERR: From<DerError> + From<ErrorKind>;

```

I can't throw my error from a sequence for example :sob: :sob:

```rust
impl<'a> DecodeValue<'a> for SequenceRef<'a> {
    type Error = Error; // <-- here it's fixed to der::Error
```

... or a `#[derive(Sequence)]` :sob:
```rust
impl #impl_generics ::der::DecodeValue<#lifetime> for #ident #ty_generics #where_clause {
    type Error = ::der::Error;
```

**Comment by tarcieri** [comment] 2024-10-05 14:29
@dishmaker I already [asked you once to act like an adult when posting to this issue tracker](https://github.com/RustCrypto/formats/issues/1228#issuecomment-1731357614). We don't have a formal CoC, but please don't make me ask you again or I may have to take action including limiting your ability to interact with this project. Posts filled with crying face emojis are not appropriate here.

> Omg why are these generic Errors on a Decode trait 

To enable format-specific custom error types, exactly as stated in the description.

> It would be a lot better on Reader trait.

That's something we can consider separately (and also a false dichotomy). Since we only have two reader types and their error cases are all covered it's not a terribly pressing issue IMO.

Note that custom error types on the `Reader` trait don't solve the OP's problem, which is errors which are specific to a particular encoding format.

> ... or a #[derive(Sequence)]

A way to override the error type when using custom derive is an important missing feature that should be easy to add.

**Comment by dishmaker** [comment] 2024-10-06 17:55
> which is errors which are specific to a particular encoding format.

In my opinion having generic `Reader::ERR` is a lot better. 
I've used it in production and such errors are really useful to track from which sequence and field the error originates.
For example `wrap_err_field` https://github.com/RustCrypto/formats/issues/1053#issuecomment-1733451601

Another argument in favor of generic Reader error is the removal of IO ErrorKind from the `der::Error`
https://github.com/RustCrypto/formats/blob/64ca37f2dee9757073829b1a9cfa40af9a20cfaf/der/src/error.rs#L196
 and making them possible only with IO readers.

**Comment by dishmaker** [comment] 2024-10-06 19:16
> Is there any specific way it should be done?

Of course just using `Reader::ERR` would be easier. 
Then the entire tree of `SEQUENCE -> SET OF -> SEQUENCE -> etc.` would use the given error type.

**Comment by tarcieri** [comment] 2024-10-06 19:46
> Maybe something like `#[asn1(error = MyError)]` on the type?

@turbocool3r yes, that sounds good to me

**Comment by tarcieri** [comment] 2024-10-06 19:48
@dishmaker your replies are off-topic and don't actually address their question.

Please open a new issue if you want to discuss making the `Reader` type errors generic, however note in advance I don't see the value.
